# Generated by Django 3.0.8 on 2020-08-06 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_q', models.IntegerField(verbose_name='購入数')),
                ('item_id', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, to='items.Item', verbose_name='商品ID')),
                ('pay_id', models.ForeignKey(db_column='pay_id', on_delete=django.db.models.deletion.PROTECT, to='payments.Payment', verbose_name='支払い情報ID')),
            ],
            options={
                'verbose_name': '支払い情報',
                'verbose_name_plural': 'payment_role',
                'db_table': 'payment_role',
            },
        ),
    ]
