# Generated by Django 3.0.8 on 2020-08-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Eメール')),
                ('password', models.CharField(max_length=30, verbose_name='パスワード')),
                ('withdrawal_datetime', models.DateTimeField(null=True, verbose_name='退会日時')),
            ],
            options={
                'verbose_name': 'ユーザ',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
        ),
    ]
