# Generated by Django 3.0.8 on 2020-08-05 23:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=30, verbose_name='商品名')),
                ('item_img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('item_detail', models.TextField(blank=True, max_length=1000, null=True, verbose_name='商品説明')),
                ('item_price', models.IntegerField(verbose_name='値段')),
                ('item_total', models.IntegerField(verbose_name='在庫')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('store_id', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.PROTECT, to='store.Store', verbose_name='お店ID')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': 'items',
                'db_table': 'items',
            },
        ),
    ]
